### PR TITLE
Remove numpy pin compat

### PR DESCRIPTION
**Pull request by WardBrian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is trying to take a look at #10, hopefully it could also help out with OSX-ARM migration.

### CODE REVIEW

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
Does the upstream package actually use Cython at all? I cannot figure out why it depends on it

**Comment by maresb** [comment]
Good question. I found this: https://github.com/facebook/prophet/pull/231

**Comment by maresb** [comment]
And then it's effectively readded here: https://github.com/facebook/prophet/commit/7f9e4b80c1b082fd221d6e189c3938ff31ce74c1

**Comment by WardBrian** [comment]
If it was specific to Pystan it can almost certainly be removed now

**Comment by WardBrian** [comment]
Closing for now, I think upstream removing Cython should help this.

**Pull request closed without merging**
