### PR TITLE
Remove numpy pin compatible

### LINKED ISSUE #10: Package version 1.0.1 build 4 is forcing numpy upgrade to version 1.20
After this change https://github.com/conda-forge/prophet-feedstock/pull/8, build 4 of the package is now forcing a numpy upgrade to version 1.20.x on my Windows environment

### PR DESCRIPTION
**Pull request by WardBrian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hopefully closes #10. This removes the numpy pinning now that Cython is not used.

### CODE REVIEW

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
It seems the pypi builds are blocking both this and #34, #35

**Comment by WardBrian** [comment]
@conda-forge/help-pypy - this feedstock is (newly) failing on PyPy builds. Before disabling the build on PyPy I thought I would ping

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
Thanks for the ping. FWIW, builds with PyPy were passing in Sept. This seems to be using numpy 1.23.5 now. Any idea what might be going wrong? I don't know prophet. Is there something in `prophet/forecaster.py", line 336 in initialize_scales` that might be suspicious?

**Comment by mattip** [comment]
I guess one approach to figuring out what is going on, if there is a desire to add PyPy packages for prophet, is to add PyPy to the upstream CI configuration.

**Comment by WardBrian** [comment]
I will suggest that. In the mean time I don't think we'd want pypy holding up the cpython builds, so I will likely merge this with them disabled

**Comment by WardBrian** [comment]
@isuruf the compiler requirement on windows is the mingw stack, not MSVC

**Comment by WardBrian** [comment]
It seems like now this is being held up by Travis failing to clone the repository

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
@maresb @bletham thoughts on merging this?

**Comment by maresb** [comment]
If my understanding is correct, then the numpy pin_compatible is a relic from the old pystan dependency where we pickled the model, which required the same minor version of numpy as the build system. Now that we're on cmdstanpy, the model is compiled as a `.bin` which no longer relies on the numpy api, so the numpy pin is no longer relevant. This looks great to me, with the caveat that my understanding is no deeper than what I'm writing here.

**Comment by maresb** [comment]
It's too bad about PyPy, but it looks like it's failing regardless of the pin_compatible? In that case it definitely makes sense to strategically to disable it for now so that we can make progress on this and other stuff, and track down the PyPy issue independently.

**Review by maresb — APPROVED** [review]

**Pull request merged**
