### PR TITLE
Add @WardBrian as maintainer

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@WardBrian, I can access the artifacts, so I think you're running into a permissions issue. Can I add you as a maintainer?

**Comment by maresb** [comment]
@bletham, @WardBrian is very heavily involved with stan and getting their conda packages running properly. I trust him completely, and I'm certain that we very much want him here as a maintainer.

**Comment by WardBrian** [comment]
I can see but not download them. Happy to be listed as a maintainer, since this will probably be the main consumer of cmdstan on CF

**Pull request merged**
