### PR TITLE
Test with noarch on dev

### PR DESCRIPTION
**Pull request by maresb**
Hi @bletham, this PR is for a pre-release build where we can experiment with these build issues together with @candalfigomoro. This way we can publish dev builds which @candalfigomoro can install, but are not installable unless explicitly selected. For details, see [here](https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds).

Unfortunately, github doesn't allow me to open a PR into a non-existent branch. @bletham, if you are up for it, could you clone my branch and push it into the `dev` branch of conda-forge/prophet-feedstock? (Take care not to push this into `master`!)

Since Git is such a PITA, here are the commands which I think should get it done:

```bash
git remote add maresb https://github.com/maresb/prophet-feedstock
git checkout master
git checkout -b dev
git pull maresb dev
git push --set-upstream origin dev
```

### CODE REVIEW

**Comment by maresb** [comment]
As a first test, I have switched back to noarch.

@conda-forge-admin please rebuild

**Comment by maresb** [comment]
@conda-forge-admin please rerender

**Comment by candalfigomoro** [comment]
@bletham Is it possible to create a package with this change so I can try it?

**Comment by maresb** [comment]
@candalfigomoro assuming I did everything correctly, after 60-90 minutes you should be able to run `conda install -c conda-forge/label/prophet_dev -c conda-forge prophet` to install my noarch version.

**Pull request closed without merging**
